name: Depoy liebi-vost-web

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          script: whoami
